# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi = weight / (height**2) * 730

print(bmi)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [8]:
random_matrix_array = np.random.randint(1,10,size=(3,4))
random_w_datatype = random_matrix_array.astype("float64")
print(random_w_datatype)


[[7. 7. 5. 9.]
 [2. 1. 7. 3.]
 [7. 4. 2. 1.]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [7]:
import csv
import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]


def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

slug_ave2017 = np.sum(bs2017["SLG"]) / len(bs2017["SLG"])
slug_ave2018 = np.sum(bs2018["SLG"])/len(bs2018["SLG"])

print(slug_ave2017)
print(slug_ave2018)

#The average SLG for the season was better in 2017




0.39334782310154126
0.3875
